export const API_URL = process.env.REACT_APP_API_URL;

export const InputSearchDelay = 700;

export enum PermissionsLabel {
  READ = 'Чтение',
  CREATE = 'Чтение и Запись',
  NO = 'Недоступно',
}

export enum Entities {
  USER = 'USER',
  DEVICE = 'DEVICE',
  VEHICLE = 'VEHICLE',
}

export enum Permissions {
  PERMISSION_VEHICLE_READ = `PERMISSION_VEHICLE_READ`,
  PERMISSION_VEHICLE_CREATE = `PERMISSION_VEHICLE_CREATE`,
  PERMISSION_VEHICLE_EDIT = 'PERMISSION_VEHICLE_EDIT',

  SYSTEM_GLOBAL_ADMIN = 'SYSTEM_GLOBAL_ADMIN',

  PERMISSION_DEVICE_READ = `PERMISSION_DEVICE_READ`,
  PERMISSION_DEVICE_CREATE = `PERMISSION_DEVICE_CREATE`,
  PERMISSION_DEVICE_EDIT = 'PERMISSION_DEVICE_EDIT',

  PERMISSION_USER_CREATE = `PERMISSION_USER_CREATE`,
  PERMISSION_USER_READ = `PERMISSION_USER_READ`,
  PERMISSION_USER_EDIT = 'PERMISSION_USER_EDIT',
}
