export enum storageKeys {
  OFFICE = 'OFFICE',
  ATTACHMENTS_TABLE_SORTS = 'ATTACHMENTS_TABLE_SORTS',
  EVENTS_TABLE_SORTS = 'EVENTS_TABLE_SORTS',
}

export enum QueryKeys {
  USER_LIST = 'USER_LIST',
  DRIVER_LIST = 'DRIVER_LIST',
  CAR_LIST = 'CAR_LIST',
  ATTACHMENT_LIST = 'ATTACHMENT_LIST',
  ALCOLOCK_LIST = 'ALCOLOCK_LIST',
  EVENTS_LIST = 'EVENTS_LIST',
  EVENTS_ITEM = 'EVENTS_ITEM',
  MARKS_CAR = 'MARKS_CAR',
}
