export enum SortsTypes {
  asc = 'asc',
  desc = 'desc',
}

export enum SortTypes {
  byName = 'byName',
  byCar = 'byCar',
  byDriver = 'byDriver',
  byUser = 'byUser',
  bySerial = 'bySerial',
  byDate = 'byDate',
  byUserName = 'byUserName',
  byCarMake = 'byCarMake',
  byCarLicense = 'byCarLicense',
  byEventType = 'byEventType',
  byMode = 'byMode',
  byRole = 'byRole',
  byAlkozamok = 'byAlkozamok',
  byAttachment = 'byAttachment',
  byGroups = 'byGroups',
  byEmail = 'byEmail',
  byAccess = 'byAccess',
  byMake = 'byMake',
  byModel = 'byModel',
  byVin = 'byVin',
  byLicense = 'byLicense',
  byManufacture = 'byManufacture',
  NAMING = 'NAMING',
  TC = 'TC',
  SERIAL_NUMBER = 'SERIAL_NUMBER',
  WHO_LINK = 'WHO_LINK',
  OPERATING_MODE = 'OPERATING_MODE',
  DATA_INSTALLATION = 'DATA_INSTALLATION',
  DRIVER = 'DRIVER',
  DATE_CREATE = 'DATE_CREATE',
  WHO_CREATE = 'WHO_CREATE',
  USER = 'USER',
  EMAIL = 'EMAIL',
  CAR_LINK = 'CAR_LINK',
  MARK = 'MARK',
  MODEL = 'MODEL',
  VIN = 'VIN',
  GOS_NUMBER = 'GOS_NUMBER',
  DATE_OCCURRENT = 'DATE_OCCURRENT',
  CREATED_BY = 'CREATED_BY',
  TYPE_OF_EVENT = 'TYPE_OF_EVENT',
  ALCOLOKS = 'ALCOLOKS',
  STATE = 'STATE',
  PROCESS = 'PROCESS',
  EXPIRES = 'EXPIRES',
  YEAR = 'YEAR',
  ROLE = 'ROLE',
  ACCESS = 'ACCESS',
}
